### ISSUE TITLE
Install rspec 

### ISSUE THREAD

**Issue by GALTdea** [GALTdea/StartupsOnRails.com#3]
The app was generated with the default test framework. 
We need to 
- delete all the default test files 
- uninstall minitest gem? 
- install rspec gem

**Comment by adrianvalenz** [comment]
@GALTdea I went ahead and installed RSpec and a couple other gems and added a few specs for the User and Company model. I went ahead and assigned you as a reviewer so you can look at the code changes I made and approve the PR.
